### ISSUE TITLE
Update, move or delete 'Precision' and 'Implementation Notes' pages on Java.net

### ISSUE THREAD

**Issue by msgilligan** [JavaMoney/JavaMoney.github.io#13]
I'm not sure where to file an issue for this problem, but since this website links to the pages on Java.net and *may* be the correct place for the updated information, I'm creating it here.

Both the [Precision](https://java.net/projects/javamoney/pages/Precision) and [Implementation Notes](https://java.net/projects/javamoney/pages/Implementation) pages on the Java.net project refer to an implementation using '2 longs' -- which I'm pretty sure is no longer true.

Those pages should either be updated with correct information, updated with links to the latest information (perhaps in the spec?), moved to `JavaMoney.github.io`, or simply deleted.

**Comment by keilw** [comment]
The website project seems a good place for that. The date suggests it wasn't updated lately. Guess we'll align that with the spec or delete some of it on java.net and point to other documents. Thanks.

**Comment by msgilligan** [comment]
Yes, I would definitely prefer to see it on Github, where it's easy to find and easy to submit Issues and PRs for.

**Comment by atsticks** [comment]
The ïmplementation notes' page is only linked (if linked at all) for
historical reasons. I think we can safely delete it....

2015-04-13 0:45 GMT+02:00 Sean Gilligan <notifications@github.com>:

> Yes, I would definitely prefer to see it on Github, where it's easy to
> find and easy to submit Issues and PRs for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JavaMoney/JavaMoney.github.io/issues/13#issuecomment-92146079>
> .
>



-- 
*Anatole Tresch*
Java Engineer & Architect, JSR Spec Lead
Glärnischweg 10
CH - 8620 Wetzikon

*Switzerland, Europe Zurich, GMT+1*
*Twitter:  @atsticks*
*Blogs: **http://javaremarkables.blogspot.ch/
<http://javaremarkables.blogspot.ch/>*

*Google: atsticksMobile  +41-76 344 62 79*

**Comment by atsticks** [comment]
Fixed both. Thanks for pointing us to these things ;)

2015-04-13 0:45 GMT+02:00 Sean Gilligan <notifications@github.com>:

> Yes, I would definitely prefer to see it on Github, where it's easy to
> find and easy to submit Issues and PRs for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JavaMoney/JavaMoney.github.io/issues/13#issuecomment-92146079>
> .
>



-- 
*Anatole Tresch*
Java Engineer & Architect, JSR Spec Lead
Glärnischweg 10
CH - 8620 Wetzikon

*Switzerland, Europe Zurich, GMT+1*
*Twitter:  @atsticks*
*Blogs: **http://javaremarkables.blogspot.ch/
<http://javaremarkables.blogspot.ch/>*

*Google: atsticksMobile  +41-76 344 62 79*

**Comment by keilw** [comment]
Can we close the ticket or are there still other places left?

**Comment by msgilligan** [comment]
Well, @atsticks updated the pages so we could close this issue based on that. But I think the content should be moved to Github or removed if already duplicated elsewhere.

**Comment by keilw** [comment]
Will close it since the mismatch was addressed. Most of the wiki was/is about decision making and brainstorming for the design process. Not much of that would make sense in GitHub or Asciidoc form IMHO, but please feel free to create follow-up tickets if you think there's something that should really go into a tutorial or other page.

**Comment by msgilligan** [comment]
Maybe they should be deleted. I'm still a newbie on this project and when looking for answers to some questions I had I stumbled upon those pages. It became clear to me pretty quickly that they were out of date, but it was still confusing. That's why I think it would be best to either delete them or have them provide links to newer content.

I still don't know JavaMoney well enough to know which documentation is most accurate.

**Comment by keilw** [comment]
The wiki contains almost no trace of what you pointed to. And implementation details point to the latest available spec (as of now Final Draft, until PMO starts the Final Aproval Ballot). Some pages will always be sort of a "snapshot", e.g. nobody will change a detail page like: https://jcp.org/en/jsr/detail?id=354 even if there were things proposed or estimated that were later done differently.
